Resources:
  EnquiryService0AAA7EF4:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/EnquiryService/Resource
  EnquiryServiceEnquiryServiceHandlerServiceRole26F2DF79:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/EnquiryServiceHandler/ServiceRole/Resource
  EnquiryServiceEnquiryServiceHandlerServiceRoleDefaultPolicy343A6E0E:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - EnquiryService0AAA7EF4
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - EnquiryService0AAA7EF4
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: EnquiryServiceEnquiryServiceHandlerServiceRoleDefaultPolicy343A6E0E
      Roles:
        - Ref: EnquiryServiceEnquiryServiceHandlerServiceRole26F2DF79
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/EnquiryServiceHandler/ServiceRole/DefaultPolicy/Resource
  EnquiryServiceEnquiryServiceHandler0276F4DB:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameterseb979a3904f76a5219e1e926e5bd29414982bfa626aad2af3850d500b66f1df0S3Bucket340EB19C
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterseb979a3904f76a5219e1e926e5bd29414982bfa626aad2af3850d500b66f1df0S3VersionKey9F26DB97
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterseb979a3904f76a5219e1e926e5bd29414982bfa626aad2af3850d500b66f1df0S3VersionKey9F26DB97
      Role:
        Fn::GetAtt:
          - EnquiryServiceEnquiryServiceHandlerServiceRole26F2DF79
          - Arn
      Environment:
        Variables:
          BUCKET:
            Ref: EnquiryService0AAA7EF4
      Handler: EnquiryServiceHandler.main
      Runtime: nodejs14.x
    DependsOn:
      - EnquiryServiceEnquiryServiceHandlerServiceRoleDefaultPolicy343A6E0E
      - EnquiryServiceEnquiryServiceHandlerServiceRole26F2DF79
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/EnquiryServiceHandler/Resource
      aws:asset:path: /home/dusan/Workspaces/github/liz-yoga-enquiry-service-lambda/src
      aws:asset:property: Code
  EnquiryServiceenquiryapiD190EB4C:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Yoga Classes Enquiry Service.
      Name: Enquiry Service
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/enquiry-api/Resource
  EnquiryServiceenquiryapiCloudWatchRole28E2C394:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/enquiry-api/CloudWatchRole/Resource
  EnquiryServiceenquiryapiAccount275A99B4:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - EnquiryServiceenquiryapiCloudWatchRole28E2C394
          - Arn
    DependsOn:
      - EnquiryServiceenquiryapiD190EB4C
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/enquiry-api/Account
  EnquiryServiceenquiryapiDeployment1EB14AF8236aac6e550a10680f8afb9b9105b460:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: EnquiryServiceenquiryapiD190EB4C
      Description: Automatically created by the RestApi construct
    DependsOn:
      - EnquiryServiceenquiryapiOPTIONS8A12D97E
      - EnquiryServiceenquiryapiPOST2411211D
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/enquiry-api/Deployment/Resource
  EnquiryServiceenquiryapiDeploymentStageprod82434FBD:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: EnquiryServiceenquiryapiD190EB4C
      DeploymentId:
        Ref: EnquiryServiceenquiryapiDeployment1EB14AF8236aac6e550a10680f8afb9b9105b460
      StageName: prod
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/enquiry-api/DeploymentStage.prod/Resource
  EnquiryServiceenquiryapiOPTIONS8A12D97E:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId:
        Fn::GetAtt:
          - EnquiryServiceenquiryapiD190EB4C
          - RootResourceId
      RestApiId:
        Ref: EnquiryServiceenquiryapiD190EB4C
      AuthorizationType: NONE
      Integration:
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH,HEAD'"
            StatusCode: "204"
        RequestTemplates:
          application/json: "{ statusCode: 200 }"
        Type: MOCK
      MethodResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
          StatusCode: "204"
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/enquiry-api/Default/OPTIONS/Resource
  EnquiryServiceenquiryapiPOSTApiPermissionLizYogaEnquiryServiceLambdaStackEnquiryServiceenquiryapiFBB13466POST6A5114F8:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - EnquiryServiceEnquiryServiceHandler0276F4DB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EnquiryServiceenquiryapiD190EB4C
            - /
            - Ref: EnquiryServiceenquiryapiDeploymentStageprod82434FBD
            - /POST/
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/enquiry-api/Default/POST/ApiPermission.LizYogaEnquiryServiceLambdaStackEnquiryServiceenquiryapiFBB13466.POST..
  EnquiryServiceenquiryapiPOSTApiPermissionTestLizYogaEnquiryServiceLambdaStackEnquiryServiceenquiryapiFBB13466POST6B2517C9:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - EnquiryServiceEnquiryServiceHandler0276F4DB
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EnquiryServiceenquiryapiD190EB4C
            - /test-invoke-stage/POST/
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/enquiry-api/Default/POST/ApiPermission.Test.LizYogaEnquiryServiceLambdaStackEnquiryServiceenquiryapiFBB13466.POST..
  EnquiryServiceenquiryapiPOST2411211D:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Fn::GetAtt:
          - EnquiryServiceenquiryapiD190EB4C
          - RootResourceId
      RestApiId:
        Ref: EnquiryServiceenquiryapiD190EB4C
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        RequestTemplates:
          application/json: '{ "statusCode": "200" }'
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - EnquiryServiceEnquiryServiceHandler0276F4DB
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/EnquiryService/enquiry-api/Default/POST/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02Q0W6DMAxFv6XvIR0g7Xm0U9+mIfYFXvBYCklQ7KxCEf8+ElqpTz5OfH1vUsqyquXL4Q1uVKh+PEblPMr4xaBGcXaW2AfFoiFC3g4HbQdx/rGfgefAiVrwYJDRp6ZDcsErTLyJe83a2VWk5ZFqGU9BjZhld9rLCQhXMYH57kHGS7Aq6dLYM7fojSbKGzUYGTs3ZadcWzdpteS5TKuguoAUm2ROL2DWAzDeYNmkSNzM+p75gY1SLlgW7zhPbjFoc9SnLv1Attzh8dyUX3wg/7o+Xe60rquwrkd5peNfWcmqkq+HK2ld+M1DG5TdXv8BtjSRe4QBAAA=
    Metadata:
      aws:cdk:path: LizYogaEnquiryServiceLambdaStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  EnquiryServiceenquiryapiEndpoint7DF30911:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: EnquiryServiceenquiryapiD190EB4C
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: EnquiryServiceenquiryapiDeploymentStageprod82434FBD
          - /
Parameters:
  AssetParameterseb979a3904f76a5219e1e926e5bd29414982bfa626aad2af3850d500b66f1df0S3Bucket340EB19C:
    Type: String
    Description: S3 bucket for asset "eb979a3904f76a5219e1e926e5bd29414982bfa626aad2af3850d500b66f1df0"
  AssetParameterseb979a3904f76a5219e1e926e5bd29414982bfa626aad2af3850d500b66f1df0S3VersionKey9F26DB97:
    Type: String
    Description: S3 key for asset version "eb979a3904f76a5219e1e926e5bd29414982bfa626aad2af3850d500b66f1df0"
  AssetParameterseb979a3904f76a5219e1e926e5bd29414982bfa626aad2af3850d500b66f1df0ArtifactHashEC1C6143:
    Type: String
    Description: Artifact hash for asset "eb979a3904f76a5219e1e926e5bd29414982bfa626aad2af3850d500b66f1df0"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

